### PR TITLE
Add typo3cms language:update task

### PR DESCRIPTION
**Pull request by maikschneider**
When there is another language configured in `LocalConfiguration.php`, the language files of all extensions need to be updated. I would suggest to add the task after the database update task.

### CODE REVIEW

**Comment by kszymukowicz** [comment]
I am not sure if it should be automated. The BIG against is that the label can be changed in translation and if customer already accepted previous translation then I consider it FAIL.

IMO labels should be stored on git. Updated only if needed and then check locally if all is OK. Then deployed to testing instance when customer is doing quality check and finally deployed to live instance. 

If it would be automated you would need to ask customer (or make it yourself task) if labels are correct after each deploy.


So if you want to still push this PR then you would need to:
1) make this task optional at all (and make it disabled by default)
2) disable execution of this task on TYPO3 versions that does not support it

**Comment by maikschneider** [comment]
Oh, thanks for your feedback! I didn't think of this. In my case, languages are always handled by us.

I added a setting `typo3_language_update` and a shallow task `check_language_update`. This way, the `typo3cms:language:update` task is not called and visible in the default deployer output. 

Since the task is disabled by default, only users who know this works on their installation would activate this. Do you think it is still necessary to check for TYPO3 versions, that do not support this command? I tried to set up a v6 installation via composer, without luck. The version constraints conflict every time.

**Comment by kszymukowicz** [comment]
"In my case, languages are always handled by us." -> how does it help to prevent when some extension author will change label which were already accepted by your customer ?

**Comment by maikschneider** [comment]
For us, this is a really rare case. Most extensions for our customers are provided by us. If there should be an adjustment to 3rd party labels, we provide an override via `locallang.xlf` or `TCEFORM`. Sure, the key could change. However, this should be detected at extension update on local or staging host. 
I will think about versioning the `l10n` dir in the future.

**Comment by kszymukowicz** [comment]
"However, this should be detected at extension update on local or staging host." -> How do you want to detect this on staging level if you are not searching actively for language labels changes?


Think of something like that: 

- current label value "**There is no news for this category**" -> your customer likes this version
- new label value: "**No news.**" -> your customer for some reason hate this version

There is no way you can detect this on regular checks of staging because why you would need to look for the label changes when in fact you did changes to CSS and doing deployment of the CSS changes.

IMO the update of language packs would be good only for core backend labels. Nothing more.

Could you explain me why you would like to get updates of labels for frontend plugins automatically on each deploy?
This can only change state already accepted by your team and your customer.

**Comment by maikschneider** [comment]
Like I said, we rarely use translations of 3rd party extensions and I can't remember a single case where a customer complained about a changed label due to an update.

For me, it just feels bad to have an identical copy of so many files, stored in my repo, for so many projects, instead of just downloading the current version from public resource. IMO if you do not override default templates of 3rd party extensions, you have to live with the consequences of changes in upcoming versions.

But yes, you are right. If you really want to be 100% safe, you have to keep the files inside git. 

I just checked: The files are stored in `./var/labels` - have you just included this path in your git or did you move them anywhere? Do you do anything special with these translations?

**Comment by kszymukowicz** [comment]
So far I have just few TYPO3 11 as starting projects so I have yet no best practice here but so far I always had `typo3conf/l10n` in git. As far as I see in TYPO3 11 code this path for language files is not configurable so looks like I will just add `/var/labels` to git. 

In the branch `t311` I added  `/var/labels` to shared folders but I will remove it then.

I just checked that for DE language the TYPO3 core translations have 2,5MB and total 142 files. I am not sure its so much files. The space is cheap now, internet speed is big, and number of files is so low that it should not slow down anything.

**Comment by kszymukowicz** [comment]
What we can do if you will really want to use it is that we can add to repo just the task `typo3cms:language:update` without any checks (if it should be active, or for what TYPO3 version it should be on) and then anyone who want it will add just:

`after('typo3cms:database:updateschema', 'typo3cms:language:update');`

I suppose its the most simple solution.

**Comment by kszymukowicz** [comment]
@maikschneider 

I am still not convinced to run language updates on each deploy therefore all I can do is to add task `typo3cms:language:update` to `deployer-extended-typo3`. It has been added in 16.1.0

Use it just like:
```before('deploy:symlink', 'typo3cms:language:update');```

greetings

**Pull request closed without merging**
